version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend.Dockerfile
    ports:
      - "8080:80"
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend.Dockerfile
    ports:
      - "5000:5000"